---
title: "regresion lineal"
author: "Renan Escalante-Chong"
date: "8/3/2017"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(magrittr)
library(tidyr)
library(stringr)
library(readr)
library(lubridate)
library(ggmap)
```

# Modelo predictivo de temperatura por sitio

Hacer una regresion lineal por sitio
Determinar la resiliencia de cada especie
Determinar que especies van a sobrevivir en los siguientes años


```{r, include=FALSE}
temperatura_df <- read_tsv('../datos/temperatura_por_sitio.tsv')

temperatura_df %<>% mutate(day = 01)
temperatura_df %<>% mutate(fecha = str_c(year, month, day, sep = '-'))
temperatura_df$fecha <- as.Date(temperatura_df$fecha, format = "%Y-%m-%d")

```

```{r}
temperatura_df %>% filter(localidad == 'acapulco' & year == 2002) %>% ggplot() + geom_point(aes(x = fecha, y = temperatura)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Linear fit

```{r, echo=FALSE}
temperatura_df %>% filter(localidad == 'acapulco' & year == 2005) %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point() + geom_smooth(method ="lm") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

## LOESS (LOcal regrESSion)

```{r, echo=FALSE}
temperatura_df %>% filter(localidad == 'acapulco' & year == 2005) %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point() + geom_smooth(method ="loess") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

# Fit over years

```{r, echo=FALSE}
temperatura_df %>% filter(localidad == 'acapulco') %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point() + geom_smooth(method ="loess") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r, echo=FALSE}
temperatura_df %>% filter(localidad == 'acapulco') %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point() + geom_smooth(method ="loess", span = 0.8) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + facet_wrap(~year)
```

```{r, echo=FALSE}
temperatura_df %>% filter(localidad == 'acapulco') %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point(span = 0.01) + geom_smooth(method ="lm") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
model <- lm(formula = fecha ~ temperatura, temperatura_df %>% filter(localidad == 'acapulco'))


new_data <- data.frame(fecha = as.Date("2018-01-07", format = "%Y-%m-%d"), temperatura = 10000)
```

```{r, include=FALSE}
eqn <- as.character(as.expression(
  substitute(italic(y) == a + b * italic(x) * "" ,
    list(a = format(coef(model)[1], digits=3),
         b = format(coef(model)[2], digits=3)
        ))))
```

```{r}
sp <- temperatura_df %>% filter(localidad == 'acapulco') %>% ggplot(aes(x = fecha, y = temperatura)) + geom_point() + geom_smooth(method ="lm") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

sp + annotate("text", label=eqn, parse = TRUE, x = as.Date("2016-01-27", format = "%Y-%m-%d"), y = 26, hjust=1.1, vjust=-.5)

```



Find the grouping by location and fecha

```{r}
temperaturas_year_localidad <- temperatura_df %>% select(fecha, localidad, temperatura, year) %>% group_by(year, localidad) %>% nest()
```
