---
title: "graficos  interactivos"
author: "Renan Escalante-Chong"
date: "8/3/2017"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(janitor)
library(ggplot2)
library(magrittr)
library(tidyr)
library(stringr)
library(readr)
library(lubridate)
library(gganimate)
library(gapminder)
library(foreach)

```


```{r}
temperatura_df<- read_tsv("../datos/temperatura_por_sitio.tsv")
```

```{r}
temperatura_df_plot <- temperatura_df %>% group_by(year, localidad) %>% summarise(promedio_temperatura = mean(temperatura))

temperatura_df_plot %>% filter(year == '2002') %>% ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```

```{r}
temperatura_df_plot %>% filter(year == '2002') %>% ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_polar(theta = "x", direction=1) + scale_fill_gradient(low="blue", high="red")
```

```{r}
sp <- temperatura_df_plot %>%  ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura, frame = year)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_polar(theta = "x", direction=1) + scale_fill_gradient(low="blue", high="red")
```

```{r}

temperatura_df_plot %<>% filter(localidad != 'isabel')

sp <- temperatura_df_plot %>%  ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura, frame = year)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_fill_gradient(low="blue", high="red")+ coord_polar(theta = "x", direction=1)

gganimate(sp)
```

```{r}
sp <- temperatura_df_plot %>%  ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura, frame = year)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_fill_gradient(low="blue", high="red")

gganimate(sp)
```
```{r}

foreach(current_year = unique(temperatura_df_plot$year))%do%{
  temperatura_df_plot %>% filter(year == current_year) %>% ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_polar(theta = "x", direction=1) + scale_fill_gradient(low="blue", high="red")
}








```

```{r}
jpeg("/tmp/foo%02d.jpg")
for (i in 1:16) {
  
  current_year <- unique(temperatura_df_plot$year)[i]
  
  temperatura_df_plot %>% filter(year == current_year) %>% ggplot(aes(x= localidad, y = promedio_temperatura, fill = promedio_temperatura)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_polar(theta = "x", direction=1) + scale_fill_gradient(low="blue", high="red")
  
}
dev.off()
```
```{r}
make.mov <- function(){
     unlink("plot.mpg")
     system("convert -delay 0.5 plot*.jpg plot.mpg")
}
```


