---
title: "02-manipular-visualizar-datos"
author: "Renan Escalante-Chong"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: ioslides_presentation
---

```{r, include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(magrittr)
library(tidyr)
library(stringr)
library(readr)
library(lubridate)
library(ggmap)
```

Determina cual es la localidad con mas years sampled
Cual es el numero de especies por localidad

```{r}
datos_df <- read_tsv("../datos/datos_arrecifes_especies.tsv")
```

# Grouping and summarizing

Determinar el ecosistema más diverso

```{r}

localidad_diversidad_df <- datos_df %>% group_by(localidad) %>% select(localidad, especie) %>% summarise(n_distinct(especie))

year_df <- datos_df %>% group_by(localidad, year) %>% select(localidad, especie) %>% summarise(count_especies = n_distinct(especie))

```

Calcular diversidad promedio por especie por sitio

```{r}
densidad_promedio_df <- datos_df %>% group_by(especie, localidad) %>% summarise(densidad_promedio = mean(densidad))
```


```{r}
densidad_promedio_df %>% ggplot(aes(x=especie, y = densidad_promedio)) + geom_bar(stat = 'identity') +  facet_wrap(~localidad) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Recode

Los nombres están muy largos

```{r}
# str_c(unique(densidad_promedio_df$especie), collapse = "'='")

densidad_promedio_df %<>% ungroup() %>% mutate(especie = recode(especie, 'Acanthaster_planci'= 'A_P', 'Diadema_mexicanum'= 'D_M', 'Holacanthus_passer'= 'H_P', 'Isostichopus_fuscus'= 'I_P', 'Lutjanus_argentiventris'= 'L_A', 'Mycteroperca_rosacea'= 'M_R', 'Pinctada_mazatlanica'= 'P_M', 'Scarus_ghobban'= 'S_G', 'Stegastes_rectrifaenum'= 'S_R', 'Zanclus_cornutus'= "Z_C"))
```

```{r}
densidad_promedio_df %>% ggplot(aes(x=especie, y = densidad_promedio)) + geom_bar(stat = 'identity') +  facet_wrap(~localidad) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```