---
title: "04-plotly"
author: "Renan Escalante-Chong"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: ioslides_presentation
---

# Gráficos interactivos

## Load libraries

```{r, include=FALSE}
library(ggplot2)
library(readr)
library(plotly)
library(dplyr)
```

## Lear datos

```{r}
datos_df <- read_tsv("../datos/datos_arrecifes_especies.tsv")
```

## Crear un plot interactivo

```{r}

datos_df %>% filter(localidad == "isla_cerralvo") %>% ggplot(aes(x= year, y = temperatura)) + geom_point()

# datos_df %>% filter(localidad == "isla_cerralvo") %>% ggplot(aes(x= temperatura, y = densidad)) + geom_point()
```

## Cambiar Agregar texto a cada plot

```{r}
ggplot(datos_ALS,aes(x=edad,y=progresion))+ geom_point(aes(text=pacientes))
```

## Cambiar Agregar texto a cada plot

```{r}
p<-ggplot(datos_ALS,aes(x=edad,y=progresion))+ geom_point(aes(text=pacientes))
ggplotly(p)
```

## Crear gráfico de barras interactivo

```{r}
p<-ggplot(datos_ALS,aes(x=pacientes,y=progresion))+ geom_bar(stat = "identity")+ coord_flip()
p
#ggplotly(p)
```

## Crear gráfico de barras interactivo

```{r}
p<-ggplot(datos_ALS,aes(x=pacientes,y=progresion))+ geom_bar(stat = "identity")+ coord_flip()
ggplotly(p)
```


