---
title: "regresion lineal"
author: "Renan Escalante-Chong"
date: "8/3/2017"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(magrittr)
library(tidyr)
library(stringr)
library(readr)
library(lubridate)
library(ggmap)
```

```{r}
datos_df <- read_tsv("../datos/datos_arrecifes_especies.tsv")
```

```{r}
datos_df %<>% mutate(log_densidad = log10(densidad))

```


```{r}
datos_df %>% ggplot(aes(x=temperatura, y= log_densidad)) + geom_point() + facet_wrap(~especie) + theme(strip.text = element_text(face="bold", size=5)) + geom_smooth(method = lm)
```

Escoger una localidad con datos buenos

```{r}
datos_df %>% filter(localidad == 'espiritu_santo') %>% ggplot(aes(x=year, y= log_densidad)) + geom_point() + facet_wrap(localidad~especie) + theme(strip.text = element_text(face="bold", size=5)) + geom_smooth(model = lm)
```

# Modelo predictivo de temperatura por sitio

Hacer una regresion lineal por sitio
Determinar la resiliencia de cada especie
Determinar que especies van a sobrevivir en los siguientes años

```{r}
temperatura_df <- read_tsv('../datos/temperatura_por_sitio.tsv')

temperatura_df %<>% mutate(fecha = str_c(year, month, sep = '-'))

temperatura_df$temperatura <- as.numeric(temperatura_df$temperatura)

temperatura_df <- temperatura_df[!(temperatura_df$temperatura == -32767), ]

temperatura_df %>% filter(localidad == 'acapulco' & year == 2002) %>% ggplot() + geom_point(aes(x = fecha, y = temperatura)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# Modelo predictivo para todas las especies en todas las localidades

# Temperatura en 2018