---
title: "plot_fish_distribution"
author: "Renan Escalante-Chong"
date: "7/28/2017"
output: html_document
---

```{r packages, include=FALSE}
# install.packages(c("maps", "mapdata"))
library(devtools)
library(RJSONIO)
library(raster)
# install.packages("raster")
# library(rgdal)
# the github version of ggmap, which recently pulled in a small fix I had
# for a bug 
# devtools::install_github("dkahle/ggmap")
library(data.table)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(dplyr)
library(magrittr)
library(readxl)
library(janitor)
```

# Mexico plotting

```{r, include=FALSE}
world <- map_data("world")
Mexico <- world %>% filter(region == "Mexico")
```

```{r, echo=FALSE}
ggplot() + 
  geom_polygon(data = Mexico, aes(x=long, y = lat, group = group), fill = "white", color = "black", shape = 1.05) + 
  coord_fixed(1.3) +
  theme_void()

# ggsave("JapanKorea2.png", bg = "transparent")
```

```{r, include=FALSE}
datos1 <- '/Users/Renan/Documents/personal/Clubes_Ciencia/EN2_Database.xlsx' %>% read_excel(sheet = 3, skip = 1) %>% clean_names() %>% rename(codigo = código)

# Remove empty rows
datos1 %<>% slice(which(!is.na(datos1$codigo)))

# Leer coordenadas de cada sitio

coordenadas <- '/Users/Renan/Documents/personal/Clubes_Ciencia/EN2_Database.xlsx' %>% read_excel(sheet = 1) %>% clean_names()

coordenadas %<>% rename(longitude = longitud, latitude = latitud)
```

Add distribution of species

```{r, echo=FALSE}

coordenadas %>% filter(localidad == 'Manzanillo')

# coordenadas %>% mutate(latitude = 19.1138, longitude = -104.3)
coordenadas$latitude[8] <- 19.1138
coordenadas$longitude[8] <- -104.3

coordenadas$latitude[9] <- 18.0766
coordenadas$longitude[9] <- -102.7

coordenadas$latitude[4] <- 22.89
coordenadas$longitude[4] <- -109.9

coordenadas$latitude[11] <- 16.85
coordenadas$longitude[11] <- -99.82

bc_bbox <- make_bbox(lat = latitude, lon = longitude, data = coordenadas)

bc_big <- get_map(location = bc_bbox, source = "google", maptype = "terrain")

# plot the points and color them by sector
ggmap(bc_big) + 
  geom_point(data = coordenadas, mapping = aes(x = longitude, y = latitude, color = localidad))
```

